Repository HugoRCD/shelve, pull requests merged in 2025-02, with the labels that each got.

#462 feat: add shelve-button for md file
  apps/lp/public/shelve-button-dark.png
  apps/lp/public/shelve-button-light.png
Labels: feature

#471 feat(lp): Init blog section
  apps/lp/app/components/BlogPost.vue
  apps/lp/app/components/Header.vue
  apps/lp/app/pages/[...slug].vue
  apps/lp/app/pages/blog.vue
  apps/lp/app/pages/blog/[...slug].vue
  apps/lp/app/pages/blog/index.vue
  apps/lp/content.config.ts
  apps/lp/content/blog.yml
  apps/lp/content/blog/introducing-shelve-blog.md
  apps/lp/nuxt.config.ts
Labels: feature

#472 feat: Better `@nuxt/content` support
  apps/lp/app/components/landing/Faq.vue
  apps/lp/app/components/landing/Features.vue
  apps/lp/app/components/landing/Hero.vue
  apps/lp/app/pages/index.vue
  apps/lp/content.config.ts
  apps/lp/content/index.yml
Labels: feature

#473 refactor: Server improvements
  apps/shelve/auth.d.ts
  apps/shelve/nuxt.config.ts
  apps/shelve/server/api/environments/index.get.ts
  apps/shelve/server/api/github/apps/[slug]/index.delete.ts
  apps/shelve/server/api/github/apps/index.get.ts
  apps/shelve/server/api/github/repos/index.get.ts
  apps/shelve/server/api/github/secrets/index.get.ts
  apps/shelve/server/api/github/secrets/index.post.ts
  apps/shelve/server/api/mail/welcome.ts
  apps/shelve/server/api/teams/[slug]/environments/[id].put.ts
  apps/shelve/server/api/teams/[slug]/environments/index.get.ts
  apps/shelve/server/api/teams/[slug]/environments/index.post.ts
  apps/shelve/server/api/teams/[slug]/index.delete.ts
  apps/shelve/server/api/teams/[slug]/index.get.ts
  apps/shelve/server/api/teams/[slug]/index.put.ts
  apps/shelve/server/api/teams/[slug]/members/[id].delete.ts
  apps/shelve/server/api/teams/[slug]/members/[id].put.ts
  apps/shelve/server/api/teams/[slug]/members/index.post.ts
  apps/shelve/server/api/teams/[slug]/projects/[projectId]/index.delete.ts
  apps/shelve/server/api/teams/[slug]/projects/[projectId]/index.get.ts
  apps/shelve/server/api/teams/[slug]/projects/[projectId]/index.put.ts
  apps/shelve/server/api/teams/[slug]/projects/[projectId]/variables/[variableId]/index.delete.ts
  apps/shelve/server/api/teams/[slug]/projects/[projectId]/variables/[variableId]/index.put.ts
  apps/shelve/server/api/teams/[slug]/projects/[projectId]/variables/env/[envId].get.ts
  apps/shelve/server/api/teams/[slug]/projects/[projectId]/variables/index.delete.ts
  apps/shelve/server/api/teams/[slug]/projects/[projectId]/variables/index.get.ts
  apps/shelve/server/api/teams/[slug]/projects/[projectId]/variables/index.post.ts
  apps/shelve/server/api/teams/[slug]/projects/index.get.ts
  apps/shelve/server/api/teams/[slug]/projects/index.post.ts
  apps/shelve/server/api/teams/index.get.ts
  apps/shelve/server/api/teams/index.post.ts
  apps/shelve/server/api/user/index.put.ts
  apps/shelve/server/routes/auth/github.get.ts
  apps/shelve/server/routes/auth/google.get.ts
  apps/shelve/server/routes/callback/github.ts
  apps/shelve/server/services/teams.ts
  apps/shelve/server/services/user.ts
  apps/shelve/server/utils/validateAccess.ts
  package.json
  pnpm-lock.yaml
Labels: refactor

#478 refactor: Rollback from D1 to Postgres
  .github/workflows/nuxthub-shelve.yml
  apps/base/nuxt.config.ts
  apps/shelve/Dockerfile
  apps/shelve/app/composables/useFileHandling.ts
  apps/shelve/app/layouts/app.vue
  apps/shelve/auth.d.ts
  apps/shelve/drizzle.config.ts
  apps/shelve/nuxt.config.ts
  apps/shelve/package.json
  apps/shelve/server/database/column.helpers.ts
  apps/shelve/server/database/migrations/0000_third_korath.sql
  apps/shelve/server/database/migrations/meta/0000_snapshot.json
  apps/shelve/server/database/migrations/meta/_journal.json
  apps/shelve/server/database/schema.ts
  apps/shelve/server/database/zod.ts
  apps/shelve/server/routes/auth/github.get.ts
  apps/shelve/server/routes/auth/google.get.ts
  apps/shelve/server/services/projects.ts
  apps/shelve/server/services/teams.ts
  apps/shelve/server/services/variables.ts
  apps/shelve/server/utils/drizzle.ts
  packages/types/src/Project.ts
  packages/types/src/Team.ts
  packages/types/src/Token.ts
  packages/types/src/User.ts
  packages/types/src/Variables.ts
  pnpm-lock.yaml
Labels: refactor

#481 feat: admin button to delete cache
  apps/shelve/app/pages/admin/index.vue
  apps/shelve/server/api/admin/cache.delete.ts
Labels: feature

#482 feat: Brand page
  apps/base/components/CustomButton.vue
  apps/lp/app/components/BlogPost.vue
  apps/lp/app/components/brand/ColorCard.vue
  apps/lp/app/components/brand/Copy.vue
  apps/lp/app/components/brand/Header.vue
  apps/lp/app/components/brand/LogoCard.vue
  apps/lp/app/components/brand/MarkdownBadge.vue
  apps/lp/app/components/brand/Social.vue
  apps/lp/app/components/brand/TypographyShowcase.vue
  apps/lp/app/components/brand/UsageGuidelines.vue
  apps/lp/app/components/brand/Voice.vue
  apps/lp/app/pages/brand.vue
  apps/lp/content.config.ts
  apps/lp/content/brand.yml
  apps/lp/public/logo/icon-black.png
  apps/lp/public/logo/icon-black.svg
  apps/lp/public/logo/icon-white.png
  apps/lp/public/logo/icon-white.svg
  apps/lp/public/logo/logo-black.png
  apps/lp/public/logo/logo-black.svg
  apps/lp/public/logo/logo-white.png
  apps/lp/public/logo/logo-white.svg
Labels: feature

#484 feat: add `llms.txt` module
  apps/lp/app/app.vue
  apps/lp/nuxt.config.ts
  apps/lp/package.json
  pnpm-lock.yaml
Labels: feature

#485 breaking: switch from commander to citty
  apps/lp/content/docs/3.cli/1.index.md
  apps/lp/content/docs/3.cli/2.login-logout.md
  apps/lp/content/docs/3.cli/3.create.md
  apps/lp/content/docs/3.cli/4.push-pull.md
  apps/lp/package.json
  packages/cli/.env.example
  packages/cli/README.md
  packages/cli/package.json
  packages/cli/src/commands/config.ts
  packages/cli/src/commands/create.ts
  packages/cli/src/commands/generate.ts
  packages/cli/src/commands/index.ts
  packages/cli/src/commands/login.ts
  packages/cli/src/commands/logout.ts
  packages/cli/src/commands/me.ts
  packages/cli/src/commands/pull.ts
  packages/cli/src/commands/push.ts
  packages/cli/src/commands/upgrade.ts
  packages/cli/src/index.ts
  packages/types/schema.json
  pnpm-lock.yaml
Labels: breaking

#486 feat(cli): add experimental run command
  apps/lp/content/docs/3.cli/1.index.md
  apps/lp/content/docs/3.cli/2.login-logout.md
  apps/lp/content/docs/3.cli/3.create.md
  apps/lp/content/docs/3.cli/4.push-pull.md
  apps/lp/content/docs/3.cli/run.md
  apps/lp/package.json
  apps/shelve/auth.d.ts
  apps/shelve/server/api/teams/[slug]/environments/[id].get.ts
  apps/shelve/server/services/environments.ts
  packages/cli/package.json
  packages/cli/src/commands/run.ts
  packages/cli/src/index.ts
  packages/cli/src/services/environment.ts
  packages/cli/src/utils/config.ts
  packages/types/schema.json
  packages/types/src/Cli.ts
  packages/types/src/Environment.ts
  packages/types/src/Team.ts
  pnpm-lock.yaml
  shelve.json
Labels: feature

#487 feat(cli): add default env to more commands
  apps/lp/content/docs/3.cli/5.push-pull.md
  packages/cli/package.json
  packages/cli/schema.json
  packages/cli/src/commands/pull.ts
  packages/cli/src/commands/push.ts
  packages/cli/src/commands/run.ts
  packages/cli/src/services/environment.ts
Labels: feature

#488 docs: update content
  apps/lp/content/docs/3.cli/.navigation.yml
  apps/lp/content/docs/3.cli/2.index.md
  apps/lp/content/docs/3.cli/3.run.md
  apps/lp/content/docs/3.cli/6.create.md
  apps/lp/content/docs/6.contributing/2.dev-setup.md
  apps/lp/nuxt.config.ts
  apps/shelve/Dockerfile
Labels: documentation

#490 docs: improve-structure
  README.md
  apps/lp/app/app.vue
  apps/lp/app/components/Header.vue
  apps/lp/app/components/layout/Footer.vue
  apps/lp/app/components/layout/Navbar.vue
  apps/lp/app/layouts/docs.vue
  apps/lp/app/pages/blog/[...slug].vue
  apps/lp/app/pages/docs/[...slug].vue
  apps/lp/content.config.ts
  apps/lp/content/docs/1.getting-started/1.index.md
  apps/lp/content/docs/1.getting-started/2.quickstart.md
  apps/lp/content/docs/2.core-features/projects.md
  apps/lp/content/docs/2.core-features/teams.md
  apps/lp/content/docs/2.core-features/variables.md
  apps/lp/content/docs/3.cli/2.index.md
  apps/lp/content/docs/6.contributing/1.index.md
  apps/lp/content/index.yml
  apps/lp/nuxt.config.ts
  apps/lp/package.json
  packages/cli/README.md
  pnpm-lock.yaml
Labels: documentation

#492 feat: enable light mode on lp
  apps/lp/app/app.vue
  apps/lp/app/components/Header.vue
  apps/lp/app/components/Signature.vue
  apps/lp/app/components/Status.vue
  apps/lp/app/components/brand/TypographyShowcase.vue
  apps/lp/app/components/layout/Footer.vue
  apps/lp/app/components/layout/Navbar.vue
  apps/lp/app/pages/about.vue
  apps/lp/app/pages/blog/[...slug].vue
  apps/lp/app/pages/blog/index.vue
  apps/lp/app/pages/brand.vue
  apps/lp/app/pages/docs/[...slug].vue
  apps/lp/app/pages/index.vue
  apps/lp/app/pages/roadmap.vue
  apps/shelve/app/components/layout/Divider.vue
  apps/shelve/app/components/layout/NavItem.vue
  apps/shelve/app/components/team/Manager.vue
  apps/shelve/app/components/variable/GithubSync.vue
  apps/shelve/app/pages/index.vue
Labels: feature

#499 fix: replace `ni` with `@antfu/ni`
  packages/cli/package.json
  pnpm-lock.yaml
Labels: bug

#500 fix: handle env duplicates
  apps/shelve/app/composables/useVariables.ts
Labels: bug

#501 enhancement: Shift + click to select multiples variables
  apps/shelve/app/components/variable/Create.vue
  apps/shelve/app/components/variable/Item.vue
  apps/shelve/app/components/variable/Selector.vue
  apps/shelve/app/pages/[teamSlug]/projects/[projectId]/index/variables.vue
Labels: enhancement

#503 fix: handle the case where a key has multiple values
  apps/lp/package.json
  apps/shelve/app/components/variable/Create.vue
  package.json
  pnpm-lock.yaml
Labels: bug

#504 fix(cli): `nr` is undefined without shamefully-hoist=true
  apps/base/components/Separator.vue
  apps/shelve/app/components/variable/Create.vue
  packages/cli/package.json
  packages/cli/src/commands/run.ts
Labels: bug

#505 feat: introduce new app navbar
  apps/base/assets/css/base.css
  apps/base/components/BgHighlight.vue
  apps/base/components/CustomButton.vue
  apps/base/components/Separator.vue
  apps/base/nuxt.config.ts
  apps/base/package.json
  apps/lp/app/components/layout/Navbar.vue
  apps/shelve/app/components/layout/NavItem.vue
  apps/shelve/app/components/layout/Navbar.vue
  apps/shelve/app/components/layout/Sidebar/Content.vue
  apps/shelve/app/components/layout/Sidebar/Index.vue
  apps/shelve/app/components/team/Manager.vue
  apps/shelve/app/composables/useAppCommands.ts
  apps/shelve/app/composables/useCommandPalette.ts
  apps/shelve/app/composables/useStore.ts
  apps/shelve/app/composables/useTeams.ts
  apps/shelve/app/layouts/app.vue
  apps/shelve/app/utils/navigation.ts
  apps/shelve/server/api/teams/[slug]/index.delete.ts
  apps/shelve/server/services/teams.ts
  packages/types/index.ts
  packages/types/src/Command.ts
  packages/types/src/Navigation.ts
  packages/types/src/Team.ts
  pnpm-lock.yaml
  shelve.json
Labels: feature
