Repository HugoRCD/shelve, pull requests merged in 2025-04, with the labels that each got.

#535 chore: remove `nuxt-og-image` pinned dependency
  apps/base/package.json
  apps/lp/package.json
  apps/shelve/package.json
  apps/vault/package.json
  pnpm-lock.yaml
Labels: dependencies

#537 feat(app): prepare UI for v2
  .github/pull_request_template.md
  .github/workflows/semantic-pull-request.yml
  apps/base/assets/css/animations.css
  apps/base/assets/css/base.css
  apps/lp/app/components/Header.vue
  apps/lp/app/components/landing/Hero.vue
  apps/lp/app/pages/blog/[...slug].vue
  apps/lp/content/index.yml
  apps/lp/nuxt.config.ts
  apps/shelve/app/components/AdminStats.vue
  apps/shelve/app/components/CommandPalette.vue
  apps/shelve/app/components/layout/Navbar.vue
  apps/shelve/app/components/layout/SectionHeader.vue
  apps/shelve/app/components/project/Item.vue
  apps/shelve/app/layouts/app.vue
  apps/shelve/app/pages/[teamSlug]/environments.vue
  apps/shelve/app/pages/[teamSlug]/index.vue
  apps/shelve/app/pages/[teamSlug]/members.vue
  apps/shelve/app/pages/[teamSlug]/settings.vue
  apps/shelve/app/pages/admin/index.vue
  apps/shelve/app/pages/admin/tests.vue
  apps/shelve/app/pages/user/integrations/github.vue
  apps/shelve/app/pages/user/integrations/index.vue
  apps/shelve/app/pages/user/profile.vue
  apps/shelve/app/pages/user/settings.vue
  apps/shelve/app/pages/user/tokens.vue
  apps/shelve/nuxt.config.ts
  package.json
Labels: feature

#538 refactor(app): improve ui logic
  README.md
  apps/shelve/app/assets/icons/nucleo/algorithm.svg
  apps/shelve/app/assets/icons/nucleo/blocks.svg
  apps/shelve/app/assets/icons/nucleo/bookmark.svg
  apps/shelve/app/assets/icons/nucleo/cloud.svg
  apps/shelve/app/assets/icons/nucleo/cog.svg
  apps/shelve/app/assets/icons/nucleo/exit.svg
  apps/shelve/app/assets/icons/nucleo/gear-2.svg
  apps/shelve/app/assets/icons/nucleo/house.svg
  apps/shelve/app/assets/icons/nucleo/key.svg
  apps/shelve/app/assets/icons/nucleo/list-checkbox.svg
  apps/shelve/app/assets/icons/nucleo/shield-check.svg
  apps/shelve/app/assets/icons/nucleo/user.svg
  apps/shelve/app/assets/icons/nucleo/users.svg
  apps/shelve/app/assets/icons/nucleo/zoom.svg
  apps/shelve/app/components/PageSection.vue
  apps/shelve/app/components/layout/SectionHeader.vue
  apps/shelve/app/components/project/Item.vue
  apps/shelve/app/components/project/MainSection.vue
  apps/shelve/app/components/token/Toggle.vue
  apps/shelve/app/layouts/app.vue
  apps/shelve/app/pages/[teamSlug]/environments.vue
  apps/shelve/app/pages/[teamSlug]/index.vue
  apps/shelve/app/pages/[teamSlug]/members.vue
  apps/shelve/app/pages/[teamSlug]/projects/[projectId]/index.vue
  apps/shelve/app/pages/[teamSlug]/projects/[projectId]/index/files.vue
  apps/shelve/app/pages/[teamSlug]/projects/[projectId]/index/settings.vue
  apps/shelve/app/pages/[teamSlug]/settings.vue
  apps/shelve/app/pages/admin/index.vue
  apps/shelve/app/pages/admin/tests.vue
  apps/shelve/app/pages/user/integrations/github.vue
  apps/shelve/app/pages/user/integrations/index.vue
  apps/shelve/app/pages/user/profile.vue
  apps/shelve/app/pages/user/settings.vue
  apps/shelve/app/pages/user/tokens.vue
  apps/shelve/app/utils/navigation.ts
  packages/cli/README.md
Labels: refactor

#539 feat: prepare 2.0
  apps/base/components/CrossedDiv.vue
  apps/base/components/ShelveMeta.vue
  apps/lp/app/app.vue
  apps/lp/app/components/BlogPost.vue
  apps/lp/app/components/landing/Features.vue
  apps/lp/app/pages/blog/[...slug].vue
  apps/lp/app/pages/docs/[...slug].vue
  apps/lp/app/pages/index.vue
  apps/lp/content.config.ts
  apps/lp/content/blog/announcing-2.0.md
  apps/lp/nuxt.config.ts
  apps/lp/package.json
  apps/lp/public/blog/2.0-release.png
  package.json
  packages/cli/shelve.json
Labels: feature

#542 fix(lp): hydrations error
  apps/base/components/ScrambleText.vue
  apps/base/components/ShelveMeta.vue
  apps/lp/app/app.vue
  apps/lp/app/components/Header.vue
  apps/lp/app/components/landing/Features.vue
  apps/lp/app/layouts/docs.vue
  apps/lp/app/pages/blog/[...slug].vue
  apps/lp/app/pages/docs/[...slug].vue
  apps/lp/app/pages/index.vue
  apps/lp/nuxt.config.ts
Labels: bug

#544 enhancement(app): overall post 2.0 improvements
  apps/shelve/app/assets/css/index.css
  apps/shelve/app/components/setting/ThemeToggle.vue
  apps/shelve/app/composables/useTeams.ts
  apps/shelve/app/layouts/auth.vue
  apps/shelve/app/pages/admin/index.vue
  apps/shelve/app/pages/onboarding.vue
  apps/shelve/nuxt.config.ts
  apps/shelve/server/api/admin/users/[id].delete.ts
  apps/shelve/server/api/user/index.delete.ts
  apps/shelve/server/services/github.ts
Labels: enhancement

#545 feat(app): improve GitHub apps flow
  apps/shelve/.env.example
  apps/shelve/app/composables/useTeams.ts
  apps/shelve/app/pages/admin/index.vue
  apps/shelve/app/pages/onboarding.vue
  apps/shelve/app/pages/user/integrations/github.vue
  apps/shelve/nuxt.config.ts
  apps/shelve/server/api/github/apps/[installationId]/index.delete.ts
  apps/shelve/server/api/github/apps/[slug]/index.delete.ts
  apps/shelve/server/api/github/apps/complete.get.ts
  apps/shelve/server/api/github/repos/index.get.ts
  apps/shelve/server/api/github/secrets/index.get.ts
  apps/shelve/server/database/migrations/0000_rich_avengers.sql
  apps/shelve/server/database/migrations/meta/0000_snapshot.json
  apps/shelve/server/database/migrations/meta/_journal.json
  apps/shelve/server/database/schema.ts
  apps/shelve/server/routes/callback/github.ts
  apps/shelve/server/services/github.ts
  docker/.env.example
  docker/app-compose.community.yml
  docker/app-compose.coolify.yml
  docker/app-compose.local.yml
  packages/types/src/integrations/Github.ts
Labels: feature

#549 feat(app): add `useGitHub` composable
  apps/lp/app/components/Header.vue
  apps/lp/app/pages/docs/[...slug].vue
  apps/shelve/app/components/project/RepoSelector.vue
  apps/shelve/app/composables/useGitHub.ts
  apps/shelve/app/pages/admin/index.vue
  apps/shelve/server/api/github/repos/index.get.ts
  apps/shelve/server/api/github/secrets/index.post.ts
  apps/shelve/server/services/github.ts
Labels: feature

#546 chore(app): improve `app-compose.coolify.yml`
  docker/app-compose.coolify.yml
Labels: dependencies

#552 fix(lp): nuxt-visitors throwing error
  apps/base/package.json
  pnpm-lock.yaml
Labels: bug

#554 feat(app): various improuvements
  apps/base/assets/css/base.css
  apps/base/components/Logo.vue
  apps/lp/app/assets/css/index.css
  apps/lp/public/og.png
  apps/shelve/app/assets/css/index.css
  apps/shelve/app/components/variable/Item.vue
  apps/shelve/app/pages/login.vue
  apps/shelve/public/og.png
  apps/shelve/server/database/schema.ts
  apps/vault/app/app.vue
  apps/vault/app/assets/css/index.css
  apps/vault/app/pages/decrypt.vue
  apps/vault/app/pages/index.vue
  apps/vault/server/services/vault.service.ts
Labels: feature
